---
- name: Provision template VM.
  hosts: localhost
  gather_facts: no
  tasks: 
  - name: Create web instance.
    vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: False
      folder: "{{ folder_path }}"
      name: web
      state: poweredon
      template: "{{ template_name }}"
      datacenter: "{{ datacenter_name }}"
      datastore: "{{ datastore_name }}"
      cluster: "{{ cluster_name }}"
      networks:
      - name: VM Network
        ip: "{{ web1_hosts }}"
        netmask: 255.255.255.0
        gateway: "{{ gateway_ip }}"
        type: static
        dns_servers: "{{ dns_ip }}"
      wait_for_ip_address: no

  - name: Create db instance.                    
    vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: False
      folder: "{{ folder_path }}" 
      name: db     
      state: poweredon
      template: "{{ template_name }}"
      datacenter: "{{ datacenter_name }}"
      datastore: "{{ datastore_name }}"
      cluster: "{{ cluster_name }}"
      networks:
      - name: VM Network
        ip: "{{ db1_hosts }}"
        netmask: "255.255.255.0"
        gateway: "{{ gateway_ip }}"
        device_type: vmxnet3
        dns_servers: "{{ dns_ip }}"
      wait_for_ip_address: no
