---
# Tasks file for configuring network on ubuntu 18.04
- name: Remove VMware network interfaces.
  file:
    path: /etc/network/interfaces
    state: absent
  become: yes

- name: Remove network interfaces before VMware customization.
  file:
    path: /etc/network/interfaces.BeforeVMwareCustomization
    state: absent
  become: yes

- name: Remove network.d directory.
  file:
    path: /etc/network/interfaces.d
    state: absent
  become: yes

- name: Create new network netplan.
  template:
    src: ens160-netplan.yml.j2
    dest: /etc/netplan/01-network-manager-all.yaml
  become: yes

- name: Restart Networking.
  service:
    name: networking
    state: restarted
  become: yes

- name: Apply Netplan
  command: sudo netplan apply
  async: 45
  poll: 0
  become: yes

- name: Delete Netplan to avoid error.
  command: sudo nmcli connection delete netplan-ens160
  async: 45
  poll: 0
  become: yes

- name: Apply Netplan
  command: sudo netplan apply
  async: 45
  poll: 0
  become: yes
