---
# tasks file for web
- name: Install Apache & MySQL Client
  apt:
    name: ['apache2', 'mysql-client']
    state: present
    update_cache: yes
  become: yes

- name: Start Apache
  service:
    name: apache2
    state: started
    enabled: yes
  become: yes
