---
# tasks file for common
- name: Update all packages
  yum:
    name: '*'
    state: latest
    update_cache: yes
  become: yes
- name: Install PHP, PHP mod, & git.
  yum:
    name: ['epel-release', 'php', 'libapache2-mod-php', 'php-curl', 'php-xml', 'php-mysql', 'git']
    state: present
    update_cache: yes
  become: yes
