---
# tasks file for common
- name: Update all packages
  apt:
    name: '*'
    state: latest
    update_cache: yes
  become: yes
- name: Install PHP, PHP mod, & git.
  apt:
    name: ['php', 'libapache2-mod-php', 'php-curl', 'php-xml', 'php-mysql', 'git']
    state: present
  become: yes
